services:
  notification_service:
    build: .
    env_file:
      - .env
    depends_on:
      - notifications_db
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  notifications_db:
    image: mongo:6
    container_name: notifications_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  tests:
    build: .
    container_name: notifications_api_tests
    environment:
      - MONGO_URL=${MONGO_URL}
      - DEBUG=${DEBUG}
      - PROJECT_NAME=${PROJECT_NAME}
    volumes:
      - .:/app
    command: [ "pytest", "-v", "--disable-warnings" ]
    restart: "no"


volumes:
  mongo_data: